struct Strings {
    static let statementNavigationTitle = String(localized: "statement.navigation.title", bundle: .module, comment: nil)
    static let tryAgainButton = String(localized: "error.try.again.button", bundle: .module, comment: nil)
    static let errorGenericTitle = String(localized: "error.generic.title", bundle: .module, comment: nil)
    static let closeButton = String(localized: "error.close.button", bundle: .module, comment: nil)
    static let receiptNavigationTitle = String(localized: "receipt.navigation.title", bundle: .module, comment: nil)
    static let receiptShareButtonTitle = String(localized: "receipt.share.button.title", bundle: .module, comment: nil)
    static let receiptValueTitle = String(localized: "receipt.value.title", bundle: .module, comment: nil)
    static let receiptDateTitle = String(localized: "receipt.date.title", bundle: .module, comment: nil)
    static let receiptOriginTitle = String(localized: "receipt.origin.title", bundle: .module, comment: nil)
    static let receiptDestinationTitle = String(localized: "receipt.destination.title", bundle: .module, comment: nil)
    static let receiptDescriptionTitle = String(localized: "receipt.description.title", bundle: .module, comment: nil)
    static let receiptDescriptionText = String(localized: "receipt.description.text", bundle: .module, comment: nil)
    static let filterOptionAll = String(localized: "filter.option.all", bundle: .module, comment: nil)
    static let filterOptionOutgoing = String(localized: "filter.option.outgoing", bundle: .module, comment: nil)
    static let filterOptionIncoming = String(localized: "filter.option.incoming", bundle: .module, comment: nil)
    static let filterOptionFuture = String(localized: "filter.option.future", bundle: .module, comment: nil)
}
